### PR TITLE
Minor spelling and grammar corrections

### PR DESCRIPTION
**Pull request by stevesbrain**

### CODE REVIEW

**Comment by stevesbrain** [comment]
@thinkst Is there something you'd like me to improve upon with this? Or just not interested in improving the English of the repository? Just want to know if I didn't open the PR correctly :)

**Comment by thinkst** [comment]
Hey @stevesbrain,

Thanks so much for PR request (and sorry that we missed this for so long!). We will be on top of these these going forward! 

As a thanks (and to say sorry), please let us send you some Canary swag. (if you drop us a shipping address, we will make it happen!).

**Comment by stevesbrain** [comment]
@thinkst No worries - I understand things can get busy :) And sure, happy to receive some - that's very kind! Don't mind representing Canary wherever I go :) What's the best way to get this address to you? Happy to either email it to a preferred email, or, I am happy to paste it here GPG encrypted if you prefer - just let me know! Thanks :D

**Comment by stevesbrain** [comment]
@thinkst Have sent it through just now - thanks :)

**Pull request merged**
